name: CI

on:
  push:
    branches:
      - master
  pull_request:
env:
  CI: true

jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      matrix:
        # Run only on Node 12 while repo is private to save minutes
        # node-version: [12, 14]
        node-version: [12]
        # don't include macOS-latest while repo is private because it is charged at 10x rate
        # same with windows-latest charged at 2x rate
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm build --filter ./packages
    - run: pnpm test
  Examples:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      matrix:
        # Run only on Node 12 while repo is private to save minutes
        # node-version: [12, 14]
        node-version: [12]
        # don't include macOS-latest while repo is private because it is charged at 10x rate
        # same with windows-latest charged at 2x rate
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm -r build
#  Lint:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: actions/setup-node@v1
#    - run: npm install -g pnpm
#    - run: pnpm install --frozen-lockfile
#    - run: pnpm lint
