name: Update Template

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/kit'
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out kit repository
        uses: actions/checkout@v2
        with:
          path: kit

      - name: Check out template repository
        uses: actions/checkout@v2
        with:
          ssh-key: "${{ secrets.UPDATE_TEMPLATE_SSH_KEY }}"
          repository: sveltejs/kit-template-default
          path: template

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependency-path: ${{ github.workspace }}/kit/pnpm-lock.yaml

      - name: Build kit
        working-directory: ${{ github.workspace }}/kit
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Write template
        working-directory: ${{ github.workspace }}/kit/packages/create-svelte
        run: node ./scripts/update-template-repo-contents.js ${{ github.workspace }}/template

      - name: Publish
        working-directory: ${{ github.workspace }}/template
        run: |
          touch "generated-$(date +%s)"
          git config user.email "noreply@svelte.dev"
          git config user.name "[bot]"
          git add -A
          git commit -m "version $npm_package_version"
          git push -u origin main -f
